output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill

output eDP-1 {
    mode 2560x1600@120.001Hz
    pos 0 0
    res 2560x1600
    scale 1.7
    bg /const/workflow-manjaro-sway/homeDir/dotLocal/bg/Yamada_Ryo.png stretch
}
